EmployeeTrainingRegistration/Controllers/ApplicationController.cs
using System.Web.Mvc;
using BusinessLayer.Services;
using EmployeeTrainingRegistration.Custom;

namespace EmployeeTrainingRegistration.Controllers
{
    [UserSession]
    public class ApplicationController : Controller
    {
        // GET: Application
        private readonly IApplicationService _applicationService;

        public ApplicationController(IApplicationService applicationService)
        {
            _applicationService = applicationService;
        }

        [HttpGet]
        public ActionResult Index()
        {
           
            var applicationData = _applicationService.GetEmployeeDetail();

            return View(applicationData);
               
        }
    }
}

EmployeeTrainingRegistration/Controllers/CommonController.cs
using System.Web.Mvc;

namespace EmployeeTrainingRegistration.Controllers
{
    public class CommonController : Controller
    {
        // GET: Common
        public ActionResult AccessDenied()
        {
            return View();
        }
    }
}

EmployeeTrainingRegistration/Controllers/HomeController.cs
using System.Web.Mvc;
using EmployeeTrainingRegistration.Custom;
using EmployeeTrainingRegistration.DataService;

namespace EmployeeTrainingRegistration.Controllers
{
    [UserSession]
    public class HomeController : Controller
    {
        private readonly IDataAccessLayer _layer;

        public HomeController(IDataAccessLayer layer)
        {
            _layer = layer;
        }
        public ActionResult Index()
        { 
            ViewBag.Message = _layer.Connect();

            return RedirectToAction("Index", "Login");
        }

    }
}

EmployeeTrainingRegistration/Controllers/LoginController.cs
using System.Web.Mvc;
using BusinessLayer.Services;
using EmployeeTrainingRegistration.Models;

namespace EmployeeTrainingRegistration.Controllers
{
    public class LoginController : Controller
    { 
    private readonly ILoginService _loggingIn;

    public LoginController(ILoginService loggingIn)
    {
        _loggingIn = loggingIn;
    }
    public ActionResult Index()
    {
        return View();
    }
    [HttpPost]
        public ActionResult LogIntoAccount(UserAccount userAccount)
        {
            var isAuthenticated = _loggingIn.LoginResults(userAccount.EmailAddress, userAccount.Password);

            if (isAuthenticated)
            {
                var userRoleID = _loggingIn.GetUserRoleByIdResult(userAccount.EmailAddress);

                if (userRoleID != -1) // Check if a valid RoleID is retrieved
                {
                    // Successful login
                    var urlAction = userRoleID == 1 
                        ? Url.Action("Index", "Training")
                        : Url.Action("Index", "Login");

                    this.Session["CurrentUser"] = userAccount;
                    this.Session["CurrentRole"] = userRoleID;

                    return Json(new { Success = true, url = urlAction });
                }
            }
            // Return a JSON response indicating failure
            return Json(new { Success = false, ErrorMessage = "Invalid credentials!!" });
        }

    }
}
       

EmployeeTrainingRegistration/Controllers/LogoutController.cs
using System.Web.Mvc;
using EmployeeTrainingRegistration.Custom;

namespace EmployeeTrainingRegistration.Controllers
{
    [UserSession]
    public class LogoutController : Controller
    {
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        // GET: Logout
        public ActionResult Index()
        {
                Session.Clear();
                return RedirectToAction("Index", "Login");     
        }
    }

}

EmployeeTrainingRegistration/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Services;
using DataAccessLayer.Models;
using EmployeeTrainingRegistration.Models;

namespace EmployeeTrainingRegistration.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        private readonly IRegisterService _register;
        public RegisterController(IRegisterService employee)
        {
            _register = employee;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Verify(Employee employee)
        {
            if (_register.RegisterResults(employee))
            {
                // Return a JSON response indicating success
                return Json(new { Success = true, url = Url.Action("Index", "Login") });
            }
            else
            {
                // Return a JSON response indicating failure
                return Json(new { Success = false, ErrorMessage = "Unable to register user!" });
            }
        }

    }
}


 

EmployeeTrainingRegistration/Controllers/TrainingController.cs
using System.Web.Mvc;
using BusinessLayer.Services;
using EmployeeTrainingRegistration.Custom;

namespace EmployeeTrainingRegistration.Controllers
{
    [UserSession]
    public class TrainingController : Controller
    {
        private readonly ITrainingService _trainingService;

        public TrainingController(ITrainingService trainingService)
        {
            _trainingService = trainingService;
        }
        // GET: Training
        public ActionResult Index()
        {
            var trainingData = _trainingService.GetTraining();
            return View(trainingData); 

        }
        public ActionResult EnrolledList()
        {
            return View("EnrolledList");

        }
    }

}

EmployeeTrainingRegistration/Views/Application/Index.cshtml
@model List<DataAccessLayer.Models.Application>
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        .size {
            font-family: 'Times New Roman', sans-serif;
            font-size: 22px;
            font-weight: 800px;
        }
    </style>
</head>

<body>
    @*@for (int i = 0; i < Model.Count; i++)
    {
        var training = Model[i];*@
        <div class="vh-100" style="background-color: #2779e2;">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-xl-9">
                        <div class="size">
                            <h1 class="text-white mb-4">Application Form</h1>
                        </div>
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body">

                                <div class="row align-items-center py-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">ApplicationID</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        @*<p type="text" class="form-control form-control-lg" id="applicationIDInput">@training.ApplicationID</p>*@
                                        @*<input type="text" class="form-control form-control-lg" id="applicationIDInput" />*@
                                        <input type="text" class="form-control form-control-lg" id="applicationIDInput"/>

                                    </div>
                                </div>

                                <div class="row align-items-center py-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">TrainingID</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input type="text" class="form-control form-control-lg" id="trainingIDInput" />

                                    </div>
                                </div>

                                <div class="row align-items-center py-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">EmployeeID</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input type="text" class="form-control form-control-lg" />

                                    </div>
                                </div>

                                <hr class="mx-n3">

                                <div class="row align-items-center pt-4 pb-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Full name</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input type="text" class="form-control form-control-lg" />

                                    </div>
                                </div>

                                <hr class="mx-n3">

                                <div class="row align-items-center py-3">
                                    <div class="col-md-3 ps-5">
                                        <h6 class="mb-0">Date</h6>
                                    </div>
                                    <div class="col-md-9 pe-5">
                                        <input type="date" class="form-control form-control-lg" id="dateInput" />
                                    </div>
                                </div>

                                <hr class="mx-n3">

                                <div class="row align-items-center py-3">
                                    <div class="col-md-3 ps-5">

                                        <h6 class="mb-0">Upload Attactment</h6>

                                    </div>
                                    <div class="col-md-9 pe-5">

                                        <input class="form-control form-control-lg" id="formFileLg" type="file" />
                                        <div class="small text-muted mt-2">
                                            Upload your Pre-Requisites for relative training.Max file
                                            size 50 MB
                                        </div>

                                    </div>
                                </div>

                                <hr class="mx-n3">

                                <div class="px-5 py-4">
                                    <button type="submit" class="btn btn-primary btn-lg">Send application</button>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    @*}*@
    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

     <script>
            $(document).ready(function () {
                // Make an AJAX request to retrieve application data
                $.ajax({
                    url: '@Url.Action("Index", "Application")', // Use Url.Action to generate the correct URL
                    type: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        if (data && data.length > 0) {
                            // Update the input fields with the retrieved data
                            $('#applicationIDInput').val(data[0].ApplicationID);
                            $('#trainingIDInput').val(data[0].TrainingID);
                            $('#employeeIDInput').val(data[0].EmployeeID);
                        } else {
                            console.log('No data returned from the server.');
                        }
                    },
                    error: function (xhr, textStatus, errorThrown) {
                        console.error('Error: ' + textStatus, errorThrown);
                    }
                });
            });
        </script>

</body>

</html>

EmployeeTrainingRegistration/Views/Common/AccessDenied.cshtml
@{
    ViewBag.Title = "AccessDenied";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AccessDenied</h2>

EmployeeTrainingRegistration/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>
    <h1>@ViewBag.Message</h1>
    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

EmployeeTrainingRegistration/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="vendor/select2/selectLog2.min.css">
    <link rel="stylesheet" type="text/css" href="css/util.css">
    <link rel="stylesheet" type="text/css" href="~/css/mainLogin.css">
    @*<link rel="stylesheet" href="~/css/alartBox.css">*@
    <script src="~/Scripts/ValidateLogin.js"></script>
</head>
<body>
    <div>
        <div class="limiter">
            <div class="container-login100">
                <div class="wrap-login100">
                    <div class="login100-pic js-tilt" data-tilt>
                        <img src="~/images/img-01.png" alt="IMG">
                    </div>
                    <form class="login100-form validate-form" method="post">
                        <span class="login100-form-title">
                            Login
                        </span>
                        <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@ceridian.com">
                            <input class="input100" type="text" name="EmailAddress" placeholder="Email">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                            </span>
                        </div>
                        <div class="wrap-input100 validate-input" data-validate="Password is required">
                            <input class="input100" type="password" name="Password" placeholder="Password">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-lock" aria-hidden="true"></i>
                            </span>
                        </div>
                        <div class="container-login100-form-btn">
                            <button type="button" onclick="validateLogin()" class="login100-form-btn">
                                Login
                            </button>
                        </div>
                        <div class="text-center p-t-12">
                            <span class="txt1">
                                You don't have an account yet?
                            </span>
                            <a class="txt2" href="@Url.Action("Index", "Register")">
                                REGISTER NOW
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

EmployeeTrainingRegistration/Views/Logout/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta http-equiv="cache-control" content="no-cache, no-store, must-revalidate" />
        <meta http-equiv="pragma" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <script>
            sessionStorage.clear(); // or localStorage.clear();
            window.location.replace('/Login/Index');
        </script>

    </head>
<body></body>
</html>

EmployeeTrainingRegistration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>@ViewBag.Title - My ASP.NET Application</title>*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
        @RenderBody()

</body>
</html>

EmployeeTrainingRegistration/Views/Training/EnrolledList.cshtml
@{
    ViewBag.Title = "EnrolledList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enrolled Employees List</title>
    <link rel="stylesheet" type="text/css" href="~/css/training.css">
    <link rel="stylesheet" type="text/css" href="~/css/Enrolled.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Add this in your HTML head section -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script type="text/javascript" src="~/Scripts/Logout.js"></script>
</head>
<body>
    <!-- Include necessary scripts and stylesheets, such as Bootstrap -->
    <div class="topnav">
        <a class="active" href="@Url.Action("Index", "Training")">Training List</a>
        <a class="active" href="@Url.Action("EnrolledList", "Training")">Enrolled</a>
        <div class="split">
            <div style="float: right;">
                <button type="button" class="logoutButton" onclick="LogOut()">Log out</button>
            </div>
        </div>
    </div>
    <h2>Enrolled Employees List</h2>

    <table>
        <thead>
            <tr>
                <th>Training ID</th>
                <th>Training Name</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody id="enrolledList">
            <!-- List of enrolled employees will be added dynamically here -->
        </tbody>
    </table>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            // Sample data of enrolled employees
            const enrolledEmployees = [
                { id: 1, name: "John Dofe", status: "Pending" },
                { id: 2, name: "Jane Smith", status: "Approved" },
                { id: 3, name: "Bob Johnson", status: "Rejected" },
            ];

            const enrolledList = document.getElementById("enrolledList");

            // Function to create list items based on enrolled employees data
            function createEnrolledListItem(employee) {
                const listItem = document.createElement("tr");
                listItem.innerHTML = `<td>${employee.id}</td><td>${employee.name}</td><td class="${employee.status.toLowerCase()}">${employee.status}</td>`;
                return listItem;
            }

            // Display the initial list of enrolled employees
            enrolledEmployees.forEach(employee => {
                enrolledList.appendChild(createEnrolledListItem(employee));
            });

            // Example: Simulate updating the status after some time (e.g., after an approval process)
            setTimeout(() => {
                // Simulate an approval for the employee with id 1
                updateStatus(1, "Approved");
            }, 3000);

            // Function to update the status dynamically
            function updateStatus(employeeId, newStatus) {
                const employeeItem = enrolledList.querySelector(`[data-id="${employeeId}"]`);
                if (employeeItem) {
                    // Update the status text and class
                    employeeItem.querySelector(".status").textContent = newStatus;
                    employeeItem.querySelector(".status").className = newStatus.toLowerCase();
                }
            }
        });
    </script>
</body>
</html>

EmployeeTrainingRegistration/Views/Training/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<DataAccessLayer.Models.Training>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/css/training.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Add this in your HTML head section -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="~/Scripts/ApplicationForm.js"></script>
    <title>Training List</title>
    <script type="text/javascript" src="~/Scripts/Logout.js"></script>
</head>
<body>
    <!-- Include necessary scripts and stylesheets, such as Bootstrap -->
    <div class="topnav">
        <a class="active" href="@Url.Action("Index", "Training")">Training List</a>
        <a class="active" href="@Url.Action("EnrolledList", "Training")">Enrolled</a>
        <div class="split">
            <div style="float: right;">
                <button type="button" class="logoutButton" onclick="LogOut()">Log out</button>
            </div>
        </div>
    </div>
    <div class="flex-container">
        @for (int i = 0; i < Model.Count; i++)
        {
            var training = Model[i];
            <div style="padding-left:16px">
                <div class="card">
                    <div class="card-header">
                        Training ID: @training.TrainingID
                    </div>
                    <div class="card-body">
                        <p class="card-title" style="font-size:30px"><strong>@training.TrainingName</strong></p>
                        <p class="card-text">Limited Seats: @training.LimitedSeat</p>
                        <p class="card-text">Schedule Date: @training.ScheduleTime</p>
                        <p class="card-text">Deadline: @training.Deadline</p>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal_@i">View</button>
                        <a href="#" class="btn btn-primary" onclick="redirectToApplicationForm('@Url.Action("Index", "Application")')">Apply</a>
                    </div>
                </div>
            </div>
            <!-- The Modal -->
            <div class="modal fade" id="myModal_@i">
                <div class="modal-dialog modal-md custom-modal-dialog">
                    <div class="modal-content custom-modal-content">
                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h2 class="modal-title"><Strong>@training.TrainingName</Strong></h2>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            <p class="card-text"><strong>Training ID: </strong>@training.TrainingID</p>
                            <p class="card-text"><strong>Description: </strong>@training.TrainingDescription</p>
                            <p class="card-text"><strong>Department: </strong>@training.DepartmentID</p>
                            <p class="card-text"><strong>Pre-Requisite: </strong>@training.PreRequisiteID</p>
                            <p class="card-text"><strong>Schedule Date: </strong>@training.ScheduleTime</p>
                            <p class="card-text"><strong>Limited Seats: </strong>@training.LimitedSeat</p>
                            <p class="card-text"><strong>Deadline: </strong>@training.Deadline</p>
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" style="background-color: blue" onclick="redirectToApplicationForm('@Url.Action("Index", "Application")')">Apply</button>

                        </div>
                    </div>
                </div>
            </div>

        }
    </div>
</body>
</html>